export interface GenerateSchemaFromGraphQlOptions {
  importFrom?: string;
  schemaExportName?: string;
  header?: string;
}

interface IntrospectionDocument {
  data?: {
    __schema?: IntrospectionSchema;
  };
  __schema?: IntrospectionSchema;
}

interface IntrospectionSchema {
  queryType?: { name?: string | null } | null;
  types?: readonly IntrospectionType[];
}

interface IntrospectionType {
  kind: string;
  name?: string | null;
  fields?: readonly IntrospectionField[] | null;
  enumValues?: readonly { name?: string | null }[] | null;
  possibleTypes?: readonly { name?: string | null }[] | null;
}

interface IntrospectionField {
  name: string;
  type: IntrospectionTypeRef;
}

interface IntrospectionTypeRef {
  kind: string;
  name?: string | null;
  ofType?: IntrospectionTypeRef | null;
}

interface NamedTypeRef {
  name: string;
  kind: string;
  isList: boolean;
  nullable: boolean;
}

interface ResourceDescriptor {
  key: string;
  path: string;
  kind: 'collection' | 'single';
  entityName: string;
  type: IntrospectionType;
}

const DEFAULT_IMPORT_FROM = 'strapi-query';
const INTERNAL_TYPE_PREFIXES = [
  '__',
  'Comments',
  'UsersPermissions',
  'ReviewWorkflows',
  'I18N',
  'Error',
  'Pagination',
  'ResponseCollectionMeta'
];

export function generateSchemaFromGraphQl(
  introspection: unknown,
  options: GenerateSchemaFromGraphQlOptions = {}
) {
  const schema = getIntrospectionSchema(introspection);
  const types = new Map(
    (schema.types ?? [])
      .filter((type): type is IntrospectionType & { name: string } => Boolean(type.name))
      .map((type) => [type.name, type])
  );
  const resources = discoverResources(schema, types);
  const resourceByTypeName = new Map(resources.map((resource) => [resource.entityName, resource]));
  const extraTypes = discoverExtraObjectTypes(resources, types, resourceByTypeName);
  const generatedTypeNames = new Set([
    ...resources.map((resource) => resource.entityName),
    ...extraTypes.map((type) => type.name)
  ]);
  const schemaExportName = options.schemaExportName ?? 'schema';
  const importFrom = options.importFrom ?? DEFAULT_IMPORT_FROM;
  const header = options.header ?? 'Generated by strapi-query from Strapi GraphQL introspection.';
  const lines: string[] = [
    `// ${header}`,
    `import { collection, defineSchema, entity, many, one, single } from '${importFrom}';`,
    ''
  ];

  for (const resource of resources) {
    lines.push(renderInterface(resource.entityName, resource.type, types, resourceByTypeName, generatedTypeNames, true), '');
  }

  for (const type of extraTypes) {
    lines.push(renderInterface(type.name, type, types, resourceByTypeName, generatedTypeNames, false), '');
  }

  lines.push(`export const ${schemaExportName} = defineSchema({`);

  resources.forEach((resource, index) => {
    const relations = discoverRelations(resource, resourceByTypeName);
    lines.push(...indentLines(renderResource(resource, relations), 2));

    if (index < resources.length - 1) {
      lines[lines.length - 1] += ',';
    }
  });

  lines.push('});', '');
  return lines.join('\n');
}

export function graphQlIntrospectionQuery() {
  return `
query StrapiQueryIntrospection {
  __schema {
    queryType {
      name
    }
    types {
      kind
      name
      fields {
        name
        type {
          kind
          name
          ofType {
            kind
            name
            ofType {
              kind
              name
              ofType {
                kind
                name
                ofType {
                  kind
                  name
                  ofType {
                    kind
                    name
                  }
                }
              }
            }
          }
        }
      }
      enumValues {
        name
      }
      possibleTypes {
        name
      }
    }
  }
}`;
}

function getIntrospectionSchema(introspection: unknown): IntrospectionSchema {
  if (!isRecord(introspection)) {
    throw new Error('GraphQL introspection result must be a JSON object.');
  }

  const document = introspection as IntrospectionDocument;
  const schema = document.data?.__schema ?? document.__schema;
  if (!schema?.types) {
    throw new Error('GraphQL introspection result must include data.__schema.types or __schema.types.');
  }

  return schema;
}

function discoverResources(
  schema: IntrospectionSchema,
  types: Map<string, IntrospectionType>
): ResourceDescriptor[] {
  const queryTypeName = schema.queryType?.name ?? 'Query';
  const queryType = types.get(queryTypeName);
  const fields = queryType?.fields ?? [];
  const descriptors = new Map<string, ResourceDescriptor>();

  for (const field of fields) {
    if (field.name.endsWith('_connection')) continue;

    const typeRef = unwrapType(field.type);
    const type = types.get(typeRef.name);
    if (!type || !isEntityObjectType(type)) continue;
    if (isInternalTypeName(typeRef.name) && typeRef.name !== 'UploadFile') continue;

    const existing = descriptors.get(typeRef.name);
    const kind = typeRef.isList ? 'collection' : 'single';
    if (existing && existing.kind === 'collection') continue;

    descriptors.set(typeRef.name, {
      key: lowerFirst(typeRef.name),
      path: pathFromQueryField(field.name, kind),
      kind,
      entityName: typeRef.name,
      type
    });
  }

  return [...descriptors.values()].sort((left, right) => left.key.localeCompare(right.key));
}

function isEntityObjectType(type: IntrospectionType) {
  if (type.kind !== 'OBJECT' || !type.name) return false;
  if (type.name.endsWith('RelationResponseCollection')) return false;

  return Boolean(type.fields?.some((field) => field.name === 'documentId')) || type.name === 'UploadFile';
}

function renderInterface(
  typeName: string,
  type: IntrospectionType,
  types: Map<string, IntrospectionType>,
  resourceByTypeName: Map<string, ResourceDescriptor>,
  generatedTypeNames: Set<string>,
  omitRelations: boolean
) {
  const fields = (type.fields ?? [])
    .filter((field) => shouldRenderField(field, resourceByTypeName, omitRelations))
    .map((field) => {
      const ref = unwrapType(field.type);
      const optional = ref.nullable ? '?' : '';
      return `  ${quotePropertyIfNeeded(field.name)}${optional}: ${typeRefToTypeScript(
        ref,
        types,
        resourceByTypeName,
        generatedTypeNames
      )};`;
    });

  if (fields.length === 0) {
    return `export interface ${typeName} {\n  [key: string]: unknown;\n}`;
  }

  return [`export interface ${typeName} {`, ...fields, '}'].join('\n');
}

function shouldRenderField(
  field: IntrospectionField,
  resourceByTypeName: Map<string, ResourceDescriptor>,
  omitRelations: boolean
) {
  if (field.name.endsWith('_connection')) return false;
  if (!omitRelations) return true;

  const ref = unwrapType(field.type);
  return !resourceByTypeName.has(ref.name);
}

function renderResource(resource: ResourceDescriptor, relations: RelationDescriptor[]) {
  const builder = resource.kind === 'collection' ? 'collection' : 'single';

  if (relations.length === 0) {
    return [`${resource.key}: ${builder}('${resource.path}', { entity: entity<${resource.entityName}>() })`];
  }

  return [
    `${resource.key}: ${builder}('${resource.path}', {`,
    `  entity: entity<${resource.entityName}>(),`,
    '  relations: {',
    ...relations.map((relation, index) => {
      const factory = relation.cardinality === 'one' ? 'one' : 'many';
      const comma = index < relations.length - 1 ? ',' : '';
      return `    ${quotePropertyIfNeeded(relation.property)}: ${factory}('${relation.targetKey}')${comma}`;
    }),
    '  }',
    '})'
  ];
}

interface RelationDescriptor {
  property: string;
  cardinality: 'one' | 'many';
  targetKey: string;
}

function discoverRelations(
  resource: ResourceDescriptor,
  resourceByTypeName: Map<string, ResourceDescriptor>
): RelationDescriptor[] {
  return (resource.type.fields ?? [])
    .filter((field) => !field.name.endsWith('_connection'))
    .flatMap((field) => {
      const ref = unwrapType(field.type);
      const target = resourceByTypeName.get(ref.name);
      if (!target) return [];

      return [
        {
          property: field.name,
          cardinality: ref.isList ? 'many' : 'one',
          targetKey: target.key
        } satisfies RelationDescriptor
      ];
    });
}

function discoverExtraObjectTypes(
  resources: ResourceDescriptor[],
  types: Map<string, IntrospectionType>,
  resourceByTypeName: Map<string, ResourceDescriptor>
) {
  const discovered = new Map<string, IntrospectionType & { name: string }>();
  const queue = resources.flatMap((resource) => resource.type.fields ?? []);

  for (let index = 0; index < queue.length; index += 1) {
    const field = queue[index];
    if (!field) continue;

    const ref = unwrapType(field.type);
    if (resourceByTypeName.has(ref.name) || discovered.has(ref.name)) continue;

    const type = types.get(ref.name);
    if (!type?.name || isInternalTypeName(ref.name)) continue;

    if (type.kind === 'UNION') {
      for (const possibleType of type.possibleTypes ?? []) {
        if (!possibleType.name || resourceByTypeName.has(possibleType.name) || discovered.has(possibleType.name)) {
          continue;
        }

        const possibleObjectType = types.get(possibleType.name);
        if (!possibleObjectType?.name || possibleObjectType.kind !== 'OBJECT' || isInternalTypeName(possibleType.name)) {
          continue;
        }

        discovered.set(possibleType.name, possibleObjectType as IntrospectionType & { name: string });
        queue.push(...(possibleObjectType.fields ?? []));
      }

      continue;
    }

    if (type.kind !== 'OBJECT') continue;

    discovered.set(ref.name, type as IntrospectionType & { name: string });
    queue.push(...(type.fields ?? []));
  }

  return [...discovered.values()].sort((left, right) => (left.name ?? '').localeCompare(right.name ?? ''));
}

function typeRefToTypeScript(
  ref: NamedTypeRef,
  types: Map<string, IntrospectionType>,
  resourceByTypeName: Map<string, ResourceDescriptor>,
  generatedTypeNames: Set<string>
): string {
  const namedType = namedTypeToTypeScript(ref.name, types, resourceByTypeName, generatedTypeNames);
  if (ref.isList) {
    return `${namedType}[]`;
  }

  const nullableType = ref.nullable ? `${namedType} | null` : namedType;
  return nullableType;
}

function namedTypeToTypeScript(
  name: string,
  types: Map<string, IntrospectionType>,
  resourceByTypeName: Map<string, ResourceDescriptor>,
  generatedTypeNames: Set<string>
) {
  switch (name) {
    case 'ID':
    case 'String':
    case 'Date':
    case 'DateTime':
    case 'Time':
      return 'string';
    case 'Int':
    case 'Float':
    case 'Long':
      return 'number';
    case 'Boolean':
      return 'boolean';
    case 'JSON':
      return 'unknown';
    default:
      break;
  }

  const type = types.get(name);
  if (type?.kind === 'ENUM') {
    const values = type.enumValues?.map((value) => value.name).filter((value): value is string => Boolean(value));
    return values && values.length > 0 ? values.map((value) => JSON.stringify(value)).join(' | ') : 'string';
  }

  if (type?.kind === 'UNION') {
    const values = type.possibleTypes?.map((value) => value.name).filter((value): value is string => Boolean(value));
    const generatedValues = values?.filter((value) => generatedTypeNames.has(value));
    return generatedValues && generatedValues.length > 0 ? generatedValues.join(' | ') : 'unknown';
  }

  return resourceByTypeName.get(name)?.entityName ?? (generatedTypeNames.has(name) ? name : 'unknown');
}

function unwrapType(type: IntrospectionTypeRef): NamedTypeRef {
  let current: IntrospectionTypeRef | null | undefined = type;
  let nullable = true;
  let isList = false;

  while (current) {
    if (current.kind === 'NON_NULL') {
      nullable = false;
      current = current.ofType;
      continue;
    }

    if (current.kind === 'LIST') {
      isList = true;
      current = current.ofType;
      continue;
    }

    if (!current.name) {
      throw new Error('GraphQL introspection type reference is missing a name.');
    }

    return {
      name: current.name,
      kind: current.kind,
      isList,
      nullable
    };
  }

  throw new Error('GraphQL introspection type reference is incomplete.');
}

function pathFromQueryField(fieldName: string, kind: ResourceDescriptor['kind']) {
  if (fieldName === 'uploadFiles' || fieldName === 'uploadFile') {
    return 'upload/files';
  }

  return toKebabCase(fieldName);
}

function toKebabCase(value: string) {
  return value
    .replace(/([a-z0-9])([A-Z])/g, '$1-$2')
    .replace(/_/g, '-')
    .toLowerCase();
}

function isInternalTypeName(name: string) {
  return INTERNAL_TYPE_PREFIXES.some((prefix) => name.startsWith(prefix));
}

function lowerFirst(value: string) {
  return value.slice(0, 1).toLowerCase() + value.slice(1);
}

function quotePropertyIfNeeded(value: string) {
  return /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(value) ? value : JSON.stringify(value);
}

function indentLines(lines: string[], spaces: number) {
  const indent = ' '.repeat(spaces);
  return lines.map((line) => `${indent}${line}`);
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === 'object' && value !== null && !Array.isArray(value);
}
