export interface GenerateSchemaFromStrapiSchemasOptions {
  importFrom?: string;
  schemaExportName?: string;
  header?: string;
}

export interface StrapiSchemaDocument {
  path?: string;
  schema: unknown;
}

interface StrapiSchema {
  uid?: string;
  kind?: string;
  collectionName?: string;
  info?: {
    singularName?: string;
    pluralName?: string;
    displayName?: string;
  };
  attributes?: Record<string, StrapiAttribute>;
}

interface StrapiAttribute {
  type?: string;
  required?: boolean;
  private?: boolean;
  enum?: readonly string[];
  multiple?: boolean;
  component?: string;
  repeatable?: boolean;
  components?: readonly string[];
  relation?: string;
  target?: string;
}

interface ResourceDescriptor {
  uid: string;
  key: string;
  path: string;
  kind: 'collection' | 'single';
  entityName: string;
  schema?: StrapiSchema;
  builtin?: 'uploadFile';
}

interface ComponentDescriptor {
  uid: string;
  typeName: string;
  schema: StrapiSchema;
}

interface RelationDescriptor {
  property: string;
  cardinality: 'one' | 'many';
  targetKey: string;
}

interface RenderContext {
  resourceByUid: Map<string, ResourceDescriptor>;
  componentByUid: Map<string, ComponentDescriptor>;
  includeUploadFile: boolean;
}

const DEFAULT_IMPORT_FROM = 'strapi-query';
const UPLOAD_FILE_UID = 'plugin::upload.file';

export function generateSchemaFromStrapiSchemas(
  documents: readonly StrapiSchemaDocument[],
  options: GenerateSchemaFromStrapiSchemasOptions = {}
) {
  if (documents.length === 0) {
    throw new Error('Pass at least one Strapi schema file.');
  }

  const normalized = normalizeDocuments(documents);
  const resources = normalized
    .filter((schema) => schema.kind === 'contentType')
    .map((schema) => toResourceDescriptor(schema.uid, schema.schema));
  const components = normalized
    .filter((schema) => schema.kind === 'component')
    .map((schema) => toComponentDescriptor(schema.uid, schema.schema));
  const includeUploadFile = normalized.some((schema) => hasMediaAttribute(schema.schema));

  if (includeUploadFile && !resources.some((resource) => resource.uid === UPLOAD_FILE_UID)) {
    resources.push({
      uid: UPLOAD_FILE_UID,
      key: 'uploadFile',
      path: 'upload/files',
      kind: 'collection',
      entityName: 'UploadFile',
      builtin: 'uploadFile'
    });
  }

  resources.sort((left, right) => left.key.localeCompare(right.key));
  components.sort((left, right) => left.typeName.localeCompare(right.typeName));

  const resourceByUid = new Map(resources.map((resource) => [resource.uid, resource]));
  const componentByUid = new Map(components.map((component) => [component.uid, component]));
  const context: RenderContext = { resourceByUid, componentByUid, includeUploadFile };
  const schemaExportName = options.schemaExportName ?? 'schema';
  const importFrom = options.importFrom ?? DEFAULT_IMPORT_FROM;
  const header = options.header ?? 'Generated by strapi-query from Strapi schema files.';
  const lines: string[] = [
    `// ${header}`,
    `import { collection, defineSchema, entity, many, one, single } from '${importFrom}';`,
    ''
  ];

  for (const resource of resources) {
    lines.push(renderResourceInterface(resource, context), '');
  }

  for (const component of components) {
    lines.push(renderComponentInterface(component, context), '');
  }

  lines.push(`export const ${schemaExportName} = defineSchema({`);

  resources.forEach((resource, index) => {
    const relations = discoverRelations(resource, context);
    lines.push(...indentLines(renderResource(resource, relations), 2));

    if (index < resources.length - 1) {
      lines[lines.length - 1] += ',';
    }
  });

  lines.push('});', '');
  return lines.join('\n');
}

function normalizeDocuments(documents: readonly StrapiSchemaDocument[]) {
  return documents.map((document) => {
    const schema = asStrapiSchema(document.schema);
    const kind = isContentTypeSchema(schema) ? 'contentType' : 'component';
    const uid = schema.uid ?? inferUidFromPath(document.path, kind) ?? inferUidFromSchema(schema, kind);

    if (!uid) {
      throw new Error(
        document.path
          ? `Could not infer a Strapi UID for ${document.path}.`
          : 'Could not infer a Strapi UID for a schema document.'
      );
    }

    return { uid, kind, schema };
  });
}

function asStrapiSchema(value: unknown): StrapiSchema {
  if (!isRecord(value)) {
    throw new Error('Strapi schema file must contain a JSON object.');
  }

  return value as StrapiSchema;
}

function isContentTypeSchema(schema: StrapiSchema) {
  return schema.kind === 'collectionType' || schema.kind === 'singleType';
}

function inferUidFromSchema(schema: StrapiSchema, kind: 'contentType' | 'component') {
  const singularName = schema.info?.singularName;
  if (kind === 'contentType' && singularName) {
    return `api::${singularName}.${singularName}`;
  }

  const displayName = schema.info?.displayName;
  if (kind === 'component' && displayName) {
    return `component.${toKebabCase(displayName)}`;
  }

  return undefined;
}

function inferUidFromPath(filePath: string | undefined, kind: 'contentType' | 'component') {
  if (!filePath) return undefined;

  const segments = filePath.split(/[\\/]+/).filter(Boolean);
  if (kind === 'contentType') {
    const contentTypesIndex = lastIndexOf(segments, 'content-types');
    if (contentTypesIndex > 0) {
      const apiName = segments[contentTypesIndex - 1];
      const contentTypeName = segments[contentTypesIndex + 1];
      if (apiName && contentTypeName) {
        return `api::${apiName}.${contentTypeName}`;
      }
    }

    return undefined;
  }

  const componentsIndex = lastIndexOf(segments, 'components');
  const fileName = segments[segments.length - 1];
  if (componentsIndex >= 0 && fileName) {
    const category = segments[componentsIndex + 1];
    const componentName = fileName.replace(/\.json$/i, '');
    if (category && componentName && componentName !== 'schema') {
      return `${category}.${componentName}`;
    }
  }

  return undefined;
}

function toResourceDescriptor(uid: string, schema: StrapiSchema): ResourceDescriptor {
  const apiId = uid.split('.').at(-1) ?? schema.info?.singularName ?? uid;
  const singularName = schema.info?.singularName ?? apiId;
  const pluralName = schema.info?.pluralName ?? schema.collectionName ?? `${singularName}s`;
  const kind = schema.kind === 'singleType' ? 'single' : 'collection';

  return {
    uid,
    key: toCamelCase(singularName),
    path: toKebabCase(kind === 'single' ? singularName : pluralName),
    kind,
    entityName: toPascalCase(singularName),
    schema
  };
}

function toComponentDescriptor(uid: string, schema: StrapiSchema): ComponentDescriptor {
  return {
    uid,
    typeName: `Component${toPascalCase(uid)}`,
    schema
  };
}

function renderResourceInterface(resource: ResourceDescriptor, context: RenderContext) {
  if (resource.builtin === 'uploadFile') {
    return renderInterface('UploadFile', [
      '  id: number;',
      '  documentId: string;',
      '  name: string;',
      '  alternativeText: string | null;',
      '  caption: string | null;',
      '  width: number | null;',
      '  height: number | null;',
      '  formats: unknown;',
      '  hash: string;',
      '  ext: string | null;',
      '  mime: string;',
      '  size: number;',
      '  url: string;',
      '  previewUrl: string | null;',
      '  provider: string;',
      '  provider_metadata: unknown;',
      '  createdAt: string;',
      '  updatedAt: string;'
    ]);
  }

  const fields = [
    '  id: number;',
    '  documentId: string;',
    ...attributeEntries(resource.schema)
      .filter(([, attribute]) => shouldRenderResourceAttribute(attribute))
      .map(([name, attribute]) => renderAttributeField(name, attribute, context))
      .filter((line): line is string => Boolean(line))
  ];

  return renderInterface(resource.entityName, fields);
}

function renderComponentInterface(component: ComponentDescriptor, context: RenderContext) {
  const fields = [
    '  id: number;',
    ...attributeEntries(component.schema)
      .filter(([, attribute]) => !attribute.private)
      .map(([name, attribute]) => renderAttributeField(name, attribute, context))
      .filter((line): line is string => Boolean(line))
  ];

  return renderInterface(component.typeName, fields);
}

function renderInterface(typeName: string, fields: string[]) {
  if (fields.length === 0) {
    return `export interface ${typeName} {\n  [key: string]: unknown;\n}`;
  }

  return [`export interface ${typeName} {`, ...fields, '}'].join('\n');
}

function shouldRenderResourceAttribute(attribute: StrapiAttribute) {
  return !attribute.private && attribute.type !== 'relation' && attribute.type !== 'media';
}

function renderAttributeField(name: string, attribute: StrapiAttribute, context: RenderContext) {
  const type = attributeTypeToTypeScript(attribute, context);
  if (!type) return undefined;

  return `  ${quotePropertyIfNeeded(name)}: ${type};`;
}

function attributeTypeToTypeScript(attribute: StrapiAttribute, context: RenderContext): string | undefined {
  switch (attribute.type) {
    case 'string':
    case 'text':
    case 'richtext':
    case 'email':
    case 'password':
    case 'uid':
    case 'date':
    case 'datetime':
    case 'time':
    case 'timestamp':
      return nullable(attribute, 'string');
    case 'integer':
    case 'biginteger':
    case 'float':
    case 'decimal':
      return nullable(attribute, 'number');
    case 'boolean':
      return nullable(attribute, 'boolean');
    case 'json':
    case 'blocks':
    case 'customField':
      return nullable(attribute, 'unknown');
    case 'enumeration':
      return nullable(attribute, enumType(attribute.enum));
    case 'component':
      return componentType(attribute, context);
    case 'dynamiczone':
      return dynamicZoneType(attribute, context);
    case 'media':
      return mediaType(attribute, context);
    case 'relation':
      return relationType(attribute, context);
    default:
      return nullable(attribute, 'unknown');
  }
}

function enumType(values: readonly string[] | undefined) {
  return values && values.length > 0 ? values.map((value) => JSON.stringify(value)).join(' | ') : 'string';
}

function componentType(attribute: StrapiAttribute, context: RenderContext) {
  const componentName = attribute.component ? context.componentByUid.get(attribute.component)?.typeName : undefined;
  const typeName = componentName ?? 'unknown';

  if (attribute.repeatable) {
    return `${typeName}[]`;
  }

  return nullable(attribute, typeName);
}

function dynamicZoneType(attribute: StrapiAttribute, context: RenderContext) {
  const components = attribute.components
    ?.map((uid) => context.componentByUid.get(uid))
    .filter((component): component is ComponentDescriptor => Boolean(component));

  const union = components && components.length > 0
    ? components
      .map((component) => `${component.typeName} & { __component: ${JSON.stringify(component.uid)} }`)
      .join(' | ')
    : 'unknown';

  return `(${union})[]`;
}

function mediaType(attribute: StrapiAttribute, context: RenderContext) {
  const typeName = context.includeUploadFile ? 'UploadFile' : 'unknown';
  if (attribute.multiple) {
    return `${typeName}[]`;
  }

  return nullable(attribute, typeName);
}

function relationType(attribute: StrapiAttribute, context: RenderContext) {
  const target = attribute.target ? context.resourceByUid.get(attribute.target) : undefined;
  const typeName = target?.entityName ?? 'unknown';
  const cardinality = relationCardinality(attribute);

  if (cardinality === 'many') {
    return `${typeName}[]`;
  }

  return nullable(attribute, typeName);
}

function nullable(attribute: StrapiAttribute, type: string) {
  return attribute.required ? type : `${type} | null`;
}

function discoverRelations(resource: ResourceDescriptor, context: RenderContext): RelationDescriptor[] {
  if (resource.builtin === 'uploadFile') return [];

  return attributeEntries(resource.schema).flatMap(([name, attribute]) => {
    if (attribute.private) return [];

    if (attribute.type === 'media') {
      const target = context.resourceByUid.get(UPLOAD_FILE_UID);
      if (!target) return [];

      return [{
        property: name,
        cardinality: attribute.multiple ? 'many' : 'one',
        targetKey: target.key
      }];
    }

    if (attribute.type !== 'relation' || !attribute.target) return [];

    const target = context.resourceByUid.get(attribute.target);
    if (!target) return [];

    return [{
      property: name,
      cardinality: relationCardinality(attribute),
      targetKey: target.key
    }];
  });
}

function relationCardinality(attribute: StrapiAttribute): 'one' | 'many' {
  const relation = attribute.relation ?? '';
  return relation === 'oneToMany' ||
    relation === 'manyToMany' ||
    relation === 'manyWay' ||
    relation === 'morphMany' ||
    relation === 'morphToMany'
    ? 'many'
    : 'one';
}

function renderResource(resource: ResourceDescriptor, relations: RelationDescriptor[]) {
  const builder = resource.kind === 'collection' ? 'collection' : 'single';

  if (relations.length === 0) {
    return [
      `${quotePropertyIfNeeded(resource.key)}: ${builder}('${resource.path}', { entity: entity<${resource.entityName}>() })`
    ];
  }

  return [
    `${quotePropertyIfNeeded(resource.key)}: ${builder}('${resource.path}', {`,
    `  entity: entity<${resource.entityName}>(),`,
    '  relations: {',
    ...relations.map((relation, index) => {
      const factory = relation.cardinality === 'one' ? 'one' : 'many';
      const comma = index < relations.length - 1 ? ',' : '';
      return `    ${quotePropertyIfNeeded(relation.property)}: ${factory}('${relation.targetKey}')${comma}`;
    }),
    '  }',
    '})'
  ];
}

function hasMediaAttribute(schema: StrapiSchema) {
  return attributeEntries(schema).some(([, attribute]) => attribute.type === 'media');
}

function attributeEntries(schema: StrapiSchema | undefined) {
  return Object.entries(schema?.attributes ?? {});
}

function toCamelCase(value: string) {
  const pascal = toPascalCase(value);
  return pascal.slice(0, 1).toLowerCase() + pascal.slice(1);
}

function toPascalCase(value: string) {
  return value
    .replace(/::/g, '.')
    .split(/[^A-Za-z0-9]+/)
    .filter(Boolean)
    .map((part) => part.slice(0, 1).toUpperCase() + part.slice(1))
    .join('');
}

function toKebabCase(value: string) {
  return value
    .replace(/([a-z0-9])([A-Z])/g, '$1-$2')
    .replace(/_/g, '-')
    .replace(/\s+/g, '-')
    .toLowerCase();
}

function quotePropertyIfNeeded(value: string) {
  return /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(value) ? value : JSON.stringify(value);
}

function indentLines(lines: string[], spaces: number) {
  const indent = ' '.repeat(spaces);
  return lines.map((line) => `${indent}${line}`);
}

function lastIndexOf(values: readonly string[], searchValue: string) {
  for (let index = values.length - 1; index >= 0; index -= 1) {
    if (values[index] === searchValue) return index;
  }

  return -1;
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === 'object' && value !== null && !Array.isArray(value);
}
